name: colbert
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=hac33072_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - blas=1.0=mkl
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.3.1=ha36c431_9
  - dav1d=1.2.1=hd590300_0
  - faiss-gpu=1.7.3=py3.8_h28a55e0_0_cuda11.3
  - ffmpeg=7.1.0=gpl_ha15103f_501
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc=9.4.0=h192d537_10
  - gcc_impl_linux-64=9.4.0=h03d3576_16
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gxx=9.4.0=h192d537_10
  - gxx_impl_linux-64=9.4.0=h03d3576_16
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=12.2.0=h15599e2_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libass=0.17.3=hba53ac1_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libfaiss=1.7.3=hfc2d529_0_cuda11.3
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=9.4.0=hd854feb_16
  - libgcc-ng=15.2.0=h69a702a_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.8.0.2=0
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=5.28.2=h5b01275_0
  - libsanitizer=9.4.0=h79bfe98_16
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=9.4.0=hd854feb_16
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb9d3cd8_2
  - mkl=2022.1.0=hc2b9512_224
  - ncurses=6.5=h2d0b736_3
  - numpy=1.24.4=py38h59b608b_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.47=haa7fec5_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h4a871b0_2_cpython
  - python_abi=3.8=8_cp38
  - pytorch=1.13.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - svt-av1=2.2.1=h5888daf_0
  - sysroot_linux-64=2.34=h087de78_2
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_ha0e22de_103
  - torchaudio=0.13.1=py38_cu117
  - torchvision=0.14.1=py38_cu117
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - adal==1.2.7
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - anyio==4.5.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.4.0
      - asgiref==3.8.1
      - asttokens==3.0.1
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.3.0
      - azure==4.0.0
      - azure-ai-ml==1.30.0
      - azure-ai-projects==1.0.0b10
      - azure-applicationinsights==0.1.1
      - azure-batch==4.1.3
      - azure-common==1.1.28
      - azure-core==1.33.0
      - azure-core-tracing-opentelemetry==1.0.0b12
      - azure-cosmosdb-nspkg==2.0.2
      - azure-cosmosdb-table==1.0.6
      - azure-datalake-store==0.0.53
      - azure-eventgrid==1.3.0
      - azure-graphrbac==0.40.0
      - azure-identity==1.21.0
      - azure-keyvault==1.1.0
      - azure-loganalytics==0.1.1
      - azure-mgmt==4.0.0
      - azure-mgmt-advisor==1.0.1
      - azure-mgmt-applicationinsights==0.1.1
      - azure-mgmt-authorization==0.50.0
      - azure-mgmt-batch==5.0.1
      - azure-mgmt-batchai==2.0.0
      - azure-mgmt-billing==0.2.0
      - azure-mgmt-cdn==3.1.0
      - azure-mgmt-cognitiveservices==3.0.0
      - azure-mgmt-commerce==1.0.1
      - azure-mgmt-compute==4.6.2
      - azure-mgmt-consumption==2.0.0
      - azure-mgmt-containerinstance==1.5.0
      - azure-mgmt-containerregistry==2.8.0
      - azure-mgmt-containerservice==4.4.0
      - azure-mgmt-core==1.5.0
      - azure-mgmt-cosmosdb==0.4.1
      - azure-mgmt-datafactory==0.6.0
      - azure-mgmt-datalake-analytics==0.6.0
      - azure-mgmt-datalake-nspkg==3.0.1
      - azure-mgmt-datalake-store==0.5.0
      - azure-mgmt-datamigration==1.0.0
      - azure-mgmt-devspaces==0.1.0
      - azure-mgmt-devtestlabs==2.2.0
      - azure-mgmt-dns==2.1.0
      - azure-mgmt-eventgrid==1.0.0
      - azure-mgmt-eventhub==2.6.0
      - azure-mgmt-hanaonazure==0.1.1
      - azure-mgmt-iotcentral==0.1.0
      - azure-mgmt-iothub==0.5.0
      - azure-mgmt-iothubprovisioningservices==0.2.0
      - azure-mgmt-keyvault==1.1.0
      - azure-mgmt-loganalytics==0.2.0
      - azure-mgmt-logic==3.0.0
      - azure-mgmt-machinelearningcompute==0.4.1
      - azure-mgmt-managementgroups==0.1.0
      - azure-mgmt-managementpartner==0.1.1
      - azure-mgmt-maps==0.1.0
      - azure-mgmt-marketplaceordering==0.1.0
      - azure-mgmt-media==1.0.0
      - azure-mgmt-monitor==0.5.2
      - azure-mgmt-msi==0.2.0
      - azure-mgmt-network==2.7.0
      - azure-mgmt-notificationhubs==2.1.0
      - azure-mgmt-nspkg==3.0.2
      - azure-mgmt-policyinsights==0.1.0
      - azure-mgmt-powerbiembedded==2.0.0
      - azure-mgmt-rdbms==1.9.0
      - azure-mgmt-recoveryservices==0.3.0
      - azure-mgmt-recoveryservicesbackup==0.3.0
      - azure-mgmt-redis==5.0.0
      - azure-mgmt-relay==0.1.0
      - azure-mgmt-reservations==0.2.1
      - azure-mgmt-resource==2.2.0
      - azure-mgmt-scheduler==2.0.0
      - azure-mgmt-search==2.1.0
      - azure-mgmt-servicebus==0.5.3
      - azure-mgmt-servicefabric==0.2.0
      - azure-mgmt-signalr==0.1.1
      - azure-mgmt-sql==0.9.1
      - azure-mgmt-storage==2.0.0
      - azure-mgmt-subscription==0.2.0
      - azure-mgmt-trafficmanager==0.50.0
      - azure-mgmt-web==0.35.0
      - azure-monitor-opentelemetry==1.6.12
      - azure-monitor-opentelemetry-exporter==1.0.0b40
      - azure-nspkg==3.0.2
      - azure-servicebus==0.21.1
      - azure-servicefabric==6.3.0.0
      - azure-servicemanagement-legacy==0.20.8
      - azure-storage-blob==12.26.0
      - azure-storage-common==1.4.2
      - azure-storage-file==1.4.0
      - azure-storage-file-datalake==12.21.0
      - azure-storage-file-share==12.22.0
      - azure-storage-queue==1.4.0
      - babel==2.17.0
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.14.2
      - bitarray==3.8.0
      - bleach==6.1.0
      - blinker==1.8.2
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.3
      - cryptography==46.0.3
      - datasets==3.1.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - dill==0.3.8
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - fixedint==0.1.6
      - flask==3.0.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.8
      - isodate==0.7.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - msal==1.34.0
      - msal-extensions==1.3.0
      - msrest==0.7.1
      - msrestazure==0.6.4.post1
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - oauthlib==3.3.1
      - opentelemetry-api==1.31.1
      - opentelemetry-instrumentation==0.52b1
      - opentelemetry-instrumentation-asgi==0.52b1
      - opentelemetry-instrumentation-dbapi==0.52b1
      - opentelemetry-instrumentation-django==0.52b1
      - opentelemetry-instrumentation-fastapi==0.52b1
      - opentelemetry-instrumentation-flask==0.52b1
      - opentelemetry-instrumentation-psycopg2==0.52b1
      - opentelemetry-instrumentation-requests==0.52b1
      - opentelemetry-instrumentation-urllib==0.52b1
      - opentelemetry-instrumentation-urllib3==0.52b1
      - opentelemetry-instrumentation-wsgi==0.52b1
      - opentelemetry-resource-detector-azure==0.1.5
      - opentelemetry-sdk==1.31.1
      - opentelemetry-semantic-conventions==0.52b1
      - opentelemetry-util-http==0.52b1
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pydash==8.0.5
      - pygments==2.19.2
      - pyjwt==2.9.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - strictyaml==1.7.3
      - terminado==0.18.1
      - tinycss2==1.2.1
      - tokenizers==0.20.3
      - tomli==2.3.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - ujson==5.10.0
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - xxhash==3.6.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /anaconda/envs/colbert
